apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dyn-nfs-tabpy01
  namespace: tabpy
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs"
  resources:
    requests:
      storage: 256Mi

