apiVersion: apps/v1
kind: Deployment
metadata:
  name: tabpy-deployment-aetp
  labels:
    app: tabpy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tabpy
  template:
    metadata:
      labels:
        app: tabpy
    spec:
      containers:
      - name: tabpy
        image: aetp/k8s-tabpy-aetp:first
        ports:
        - containerPort: 9004
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false

